language: php
sudo: false

php:
  - 7.2
  - 7.3

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  # Tweak composer.
  - composer config github-oauth.github.com ${GITHUB_TOKEN}
  - composer global require "hirak/prestissimo:^0.3"

  # Get the CodeClimate test reporter.
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

install:
  - COMPOSER_MEMORY_LIMIT=-1 composer install

script:
  - vendor/bin/grumphp run

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
